- name: stop SElinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: "SELINUX=disabled"
    state: present

- name: stop swapoff
  shell: swapoff -a

- name: modify /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^/dev/mapper/centos-swap'
    state: absent

- name: stop firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

